apiVersion: v1
kind: Service
metadata:
  name: foo
  labels:
    app: foo
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
spec:
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: foo
